### ISSUE TITLE
all modes failed on certain bitstream

### ISSUE THREAD

**Issue by rhwu** [lieff/minimp4#16]
Attached test2.264 (640x480) failed on all the 3 modes. But I'm able to do muxing with this bitstream using ffmpeg:
$ ffmpeg -framerate 30 -i test2.264 -c copy test2.mp4

[test2.264.zip](https://github.com/lieff/minimp4/files/4238669/test2.264.zip)

**Comment by lieff** [comment]
This stream is progressive high profile, needs to be supported in mp4_h26x_write_nal helper. Will do this at some point. Fragmentation mode + slices also currently not supported.

minimp4 still can be used in such cases, just other demuxer should be used instead of mp4_h26x_write_nal which correctly aggregates one h264 frame into sample and pass it directly to MP4E_put_sample.

**Comment by lieff** [comment]
Turns out it's trivial to fix. Problem was not in progressive encoding as I think at first, but access unit delimiter NALu`s which was not handled. This fixes default and sequential modes, for fragmentation there same issue as https://github.com/lieff/minimp4/issues/15 .
